### PR TITLE
Added yubikey ID extraction functions

### PR DESCRIPTION
**Pull request by DKhalil**
Now after calling check() you can call getYubikeyId(); to compare the set ID, or call getYubikeyID to extract the ID from an arbitrary OTP

### CODE REVIEW

**Comment by fkooman** [comment]
https://developers.yubico.com/yubikey-val/Getting_Started_Writing_Clients.html

> More generally, the YubiKey OTP contains as the initial part an identity of the YubiKey, and 
> it can be used to identify the user. The identity part is the same for every OTP, and it is the initial 
> 2-16 modhex characters of the OTP. (The identity can be programmed to 0 characters, but then 
> obviously this scheme does not apply.) Since the rest of the OTP is always 32 characters, the method
> to extract the identity is to remove 32 characters from the end and then use the remaining string, 
> which should be 2-16 characters, as the YubiKey identity.```

So taking the first 12 seems wrong...

**Comment by DKhalil** [comment]
Updated method to remove the last 32 characters instead of getting the first 12

**Comment by fkooman** [comment]
It seems using `substr($otp, 0, -32)` would be simpler :-)

**Comment by DKhalil** [comment]
Mhhhyeah, maybe, but really not by much :P

**Comment by DKhalil** [comment]
There you go!

**Comment by maclof** [comment]
@enygma any idea when you will merge this? Seems like necessary functionality to me

**Comment by enygma** [comment]
@maclof Sorry for the delay - I'll merge it now!

**Comment by maclof** [comment]
@enygma thanks buddy 👍

**Pull request merged**
